on: [ push, pull_request ]
name: CI
jobs:
  csfix:
    strategy:
      matrix:
        go-version: [ 1.14.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: run go fmt
        run: gofmt -s -w .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply go fmt changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: csfix
    strategy:
      matrix:
        go-version: [ 1.13.x, 1.14.x, 1.15.x ]
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout core
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
